 
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/USER-SERVICE
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    application:
       name: USER-SERVICE
    jpa: 
       hibernate:
        ddl-auto: update
       properties:
          hibernate:
            dialect : org.hibernate.dialect.PostgreSQLDialect 
                
eureka:
  instance:
    ip-address: true
    hostname: localhost 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
server:
    port: 8089
      
      
      