server:
  port: 8081
  
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/Microservice
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
    jpa: 
       hibernate:
        ddl-auto: update
       properties:
          hibernate:
            dialect : org.hibernate.dialect.PostgreSQLDialect 